In [1]:
import numpy as np
from os import listdir
from os.path import isfile, join
import pandas as pd
import random

path = "AmongUs_Dataset/"
files = [f for f in listdir(path) if isfile(join(path, f))]

In [2]:
Dataset = []
users_i = [0 for i in range(len(files))]

for i in range(len(files)):
#     print(files[i])
    file_path = "{}{}".format(path, files[i])
    d = pd.read_csv(file_path, delimiter=",")
    
    #add column for user id
    _id = int(files[i].split(".")[0][4:])-1
    users_i[_id] = int(len(d))
    user_id = [_id for n in range(len(d))]
    user_id_col = pd.Series(user_id, name="User_Id")
    user_data = pd.concat([d, user_id_col], axis=1)
    
    #add to compiled Dataset
    if len(Dataset) == 0:
        Dataset = user_data
    else:
        Dataset = Dataset.append(user_data)
Dataset.reset_index(drop=True, inplace=True)

In [3]:
Dataset

,Game Completed Date,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Imposter Kills,Game Length,Ejected,Sabotages Fixed,Time to complete all tasks,Rank Change,Region/Game Code,User_Id
0,12/13/2020 at 1:26:56 am EST,Crewmate,Win,3,No,Yes,-,07m 04s,No,2.0,-,++,NA / WYMSBF,0
1,12/13/2020 at 1:17:42 am EST,Crewmate,Loss,7,Yes,No,-,16m 21s,No,1.0,09m 48s,--,NA / WYMSBF,0
2,12/13/2020 at 12:57:47 am EST,Crewmate,Win,3,No,No,-,11m 33s,No,0.0,-,++,NA / WYMSBF,0
3,12/13/2020 at 12:41:55 am EST,Imposter,Win,-,-,-,2,08m 05s,No,NaN,-,+++,Europe / QIRTNF,0
4,12/13/2020 at 12:30:37 am EST,Crewmate,Loss,4,No,No,-,05m 10s,No,0.0,-,---,Europe / QIRTNF,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222,11/23/2020 at 8:41:10 pm EST,Crewmate,Win,7,Yes,No,-,21m 19s,No,0.0,05m 27s,++,NA / FOSWKF,11
2223,11/23/2020 at 8:17:56 pm EST,Crewmate,Win,7,Yes,No,-,14m 32s,No,0.0,09m 23s,++,NA / FOSWKF,11
2224,11/23/2020 at 8:02:12 pm EST,Crewmate,Loss,3,No,No,-,06m 06s,Yes,0.0,-,---,NA / FOSWKF,11
2225,11/23/2020 at 3:30:59 pm EST,Crewmate,Win,8,Yes,No,-,09m 41s,No,0.0,08m 48s,++,NA / BQVAZF,11
2226,11/23/2020 at 3:17:52 pm EST,Crewmate,Win,8,Yes,Yes,-,13m 01s,No,0.0,08m 51s,++,NA / BQVAZF,11

In [4]:
Dataset.isna().sum()

Game Completed Date             0
Team                            0
Outcome                         0
Task Completed                  0
All Tasks Completed             0
Murdered                        0
Imposter Kills                  0
Game Length                     0
Ejected                         0
Sabotages Fixed               466
Time to complete all tasks      0
Rank Change                   399
Region/Game Code                0
User_Id                         0
dtype: int64

In [13]:
df = Dataset.copy()
crewmate = df[['Team',
               'Outcome',
               'Task Completed',
               'All Tasks Completed',
               'Murdered',
               'Game Length',
               'Ejected',
              'Sabotages Fixed']][df['Team'] == 'Crewmate']
#crewmate.head()

,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Game Length,Ejected,Sabotages Fixed
0,Crewmate,Win,3,No,Yes,07m 04s,No,2.0
1,Crewmate,Loss,7,Yes,No,16m 21s,No,1.0
2,Crewmate,Win,3,No,No,11m 33s,No,0.0
4,Crewmate,Loss,4,No,No,05m 10s,No,0.0
5,Crewmate,Loss,7,Yes,Yes,16m 22s,No,0.0

In [14]:
crewmate['Outcome'] = crewmate['Outcome'].replace(['Loss', 'Win'],[0, 1])
crewmate['All Tasks Completed'] = crewmate['All Tasks Completed'].replace(['No', 'Yes'],[0, 1])
crewmate['Murdered'] = crewmate['Murdered'].replace(['No', 'Yes'],[0, 1])
crewmate['Ejected'] = crewmate['Ejected'].replace(['No', 'Yes'],[0, 1])
#crewmate.head()

,Team,Outcome,Task Completed,All Tasks Completed,Murdered,Game Length,Ejected,Sabotages Fixed
0,Crewmate,1,3,0,1,07m 04s,0,2.0
1,Crewmate,0,7,1,0,16m 21s,0,1.0
2,Crewmate,1,3,0,0,11m 33s,0,0.0
4,Crewmate,0,4,0,0,05m 10s,0,0.0
5,Crewmate,0,7,1,1,16m 22s,0,0.0

In [15]:
#Split the dataset into features and the target column
target = crewmate['Outcome']
crewmate = crewmate.drop('Outcome', axis =1)

In [17]:
crewmate.head()

,Team,Task Completed,All Tasks Completed,Murdered,Game Length,Ejected,Sabotages Fixed
0,Crewmate,3,0,1,07m 04s,0,2.0
1,Crewmate,7,1,0,16m 21s,0,1.0
2,Crewmate,3,0,0,11m 33s,0,0.0
4,Crewmate,4,0,0,05m 10s,0,0.0
5,Crewmate,7,1,1,16m 22s,0,0.0

In [18]:
target

0       1
1       0
2       1
4       0
5       0
       ..
2222    1
2223    1
2224    0
2225    1
2226    1
Name: Outcome, Length: 1761, dtype: int64

In [ ]:
def user_train_valid_split(users_i,valid_ratio,possible=False):
    n = sum(users_i)
    target = int(np.floor(valid_ratio*n))
    while not possible:
        possible, validation_indices = user_split(users_i,target)
        target -= 1
    training_indices = [i for i in range(len(users_i)) if i not in validation_indices]
    return training_indices, validation_indices

def user_split(users_i,target):  
    # Reference: https://levelup.gitconnected.com/dynamic-programming-subset-sum-c386126621cd
    n = len(users_i)
    solution = [[False for j in range(int(target+1))] for i in range(n+1)]
    # base cases
    for i in range(n):
        solution[i][0] = True
    # other cases
    for i in range(1,n+1):
        for j in range(1,target+1):
            solution[i][j] = solution[i-1][j]
            if(solution[i][j] == False and j >= users_i[i-1]):
                solution[i][j] = solution[i][j] or solution[i-1][j-users_i[i-1]]
    # check if the subset sum is possible
    possible = solution[len(users_i)][target]
    subset = []
    if not possible: return possible, subset
    # return the subset solution if one exists
    y = len(users_i)
    x = target
    while x != 0:
        if solution[y-1][x] == False:
            subset.append(y-1)
            x -= users_i[y-1]
        else: 
            y -= 1
    return possible, subset

In [ ]:
valid_ratio = .25
training_indices, validation_indices = user_train_valid_split(users_i,valid_ratio)

print(users_i)
print(training_indices, validation_indices)
train_sum = sum([users_i[i] for i in training_indices])
valid_sum = sum([users_i[i] for i in validation_indices])
print(valid_sum/(train_sum+valid_sum))

In [ ]:
train_data = Dataset.loc[Dataset['User_Id'].isin(training_indices)]
valid_data = Dataset.loc[Dataset['User_Id'].isin(validation_indices)]
train_data.reset_index(drop=True, inplace=True)
valid_data.reset_index(drop=True, inplace=True)

In [ ]:
print(len(train_data), train_sum)